# This CI Workflow runs a linter and format checker

name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  UV_VERSION: 0.8.15
  PYTHON_VERSION: 3.12

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ env.UV_VERSION }}
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Lint
      run: uv run --dev ruff check src/
      continue-on-error: true

    - name: Format Check
      run: uv run --dev ruff format --check --diff src/
